### ISSUE TITLE
Wrongly reported SveltosCluster version

### ISSUE THREAD

**Issue by prometherion** [projectsveltos/sveltoscluster-manager#133]
I have an externally managed cluster that I'd like to track with a `SveltosClustger` object.

```
NAME      VERSION   STATUS   CONTROL-PLANE ENDPOINT   KUBECONFIG                 DATASTORE   AGE
k8s-126   v1.26.0   Ready    172.18.255.201:6443      k8s-126-admin-kubeconfig   default     17d
```

Once I create the `SveltosCluster` object, it reports a wrong version:

```
NAME      READY   VERSION
k8s-126   true    v1.27.3
```

> The reported version is the management cluster one

**Comment by gianlucam76** [comment]
Thanks for reporting this. Issue has been fixed.
